[workspace]
members = [
    "api",
    "sdk",
    "crates/idns-core",
    "crates/idns-sqlite",
    "crates/idns-networks",
    "crates/idns-devices",
    "crates/idns-wasmer",
    "crates/idns-node",
]
