[package]
name = "idns-eth-sdk"
version = "0.1.0"
edition = "2021"


[lib]
name = "idns_eth_sdk_ffi"
crate-type = ["staticlib"]

[dependencies]

#IDNS.ETH
idns-eth-core = { path = "../crates/idns-core", version = "*" }
